apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-app-service
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    name: result-app-pod
    app: voting-app