apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-app-deployment
    app: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: voting-app
  template:
    metadata:
      labels:
        name: worker-app-pod
        app: voting-app
    spec:
      containers:
        - name: worker-app-container
          image: kodekloud/examplevotingapp_worker:v1
          ports:
            - containerPort: 80
